from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable


def render_cli_reference(parser: argparse.ArgumentParser | None = None) -> str:
    """Render deterministic Markdown from the same argparse tree used by the CLI."""
    if parser is None:
        from bccli.cli import build_parser

        parser = build_parser()

    sections = [
        "# BCCLI command reference",
        "",
        "<!-- Generated by `bccli docs sync`; do not edit manually. -->",
        "",
        "This file is generated from the live `argparse` command definitions, so command",
        "names, options, defaults, choices, and help text stay synchronized with the CLI.",
        "",
    ]
    for command, command_parser in _leaf_commands(parser, parser.prog):
        sections.extend(_render_command(command, command_parser))
    return "\n".join(sections).rstrip() + "\n"


def sync_cli_reference(
    output: Path,
    *,
    check: bool = False,
    parser: argparse.ArgumentParser | None = None,
) -> bool:
    """Write the generated reference, or return whether an existing file is current."""
    expected = render_cli_reference(parser)
    if check:
        try:
            return output.read_text(encoding="utf-8") == expected
        except FileNotFoundError:
            return False
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.tmp")
    temporary.write_text(expected, encoding="utf-8")
    temporary.replace(output)
    return True


def _leaf_commands(
    parser: argparse.ArgumentParser, command: str
) -> Iterable[tuple[str, argparse.ArgumentParser]]:
    subparsers = next(
        (
            action
            for action in parser._actions
            if isinstance(action, argparse._SubParsersAction)
        ),
        None,
    )
    if subparsers is None:
        yield command, parser
        return
    for name, child in subparsers.choices.items():
        yield from _leaf_commands(child, f"{command} {name}")


def _render_command(command: str, parser: argparse.ArgumentParser) -> list[str]:
    formatter = parser.formatter_class(prog=parser.prog, width=88)
    formatter.add_usage(
        parser.usage,
        parser._actions,
        parser._mutually_exclusive_groups,
    )
    usage = formatter.format_help().strip()
    if usage.lower().startswith("usage: "):
        usage = usage[7:]
    lines = [f"## `{command}`", ""]
    if parser.description:
        lines.extend([parser.description, ""])
    lines.extend(["```text", usage, "```", "", "### Options", ""])

    documented = [
        action
        for action in parser._actions
        if action.option_strings and action.help is not argparse.SUPPRESS
    ]
    if not documented:
        lines.extend(["This command has no options.", ""])
        return lines

    lines.extend(["| Option | Description |", "|---|---|"])
    for action in documented:
        option = _format_option(action)
        description = _format_description(action)
        lines.append(f"| `{_escape(option)}` | {_escape(description)} |")
    lines.append("")
    return lines


def _format_option(action: argparse.Action) -> str:
    option = ", ".join(action.option_strings)
    if action.nargs == 0:
        return option
    metavar = action.metavar
    if metavar is None:
        metavar = action.dest.upper()
    if isinstance(metavar, tuple):
        metavar = " ".join(metavar)
    return f"{option} {metavar}"


def _format_description(action: argparse.Action) -> str:
    description = action.help or ""
    if action.choices:
        choices = ", ".join(str(choice) for choice in action.choices)
        if "Types:" not in description and "choices:" not in description.lower():
            description = f"{description} Choices: {choices}."
    return " ".join(description.split())


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
